config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'users/show'
  end
  devise_for :admins, controllers: {
  registrations: "admins/registrations",
  sessions: "admins/sessions",
  passwords: "admins/passwords"
  }

  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords"
  }

  devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :movies, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :user do
    root to: 'homes#top'
    get "/about" =>"homes#about"
    resources :movies, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy] do
        resources :users, only: [:show]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.includes(:movie).all
    @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    if @review.update(review_params)
      redirect_to admin_reviews_path(@review), notice: 'レビューが更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path, notice: 'レビューを削除しました。'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to movie_path(@movie), notice: 'コメントが作成されました。'
    else
      redirect_to request.referer, alert: '入力してください！'
    end
  end

  def destroy
  @review = Review.find(params[:id])
  if @review.user == current_user
    @review.destroy
    redirect_to movie_path(@review.movie), notice: 'レビューが削除されました。'
  else
    redirect_to movie_path(@review.movie), alert: '他のユーザーのレビューは削除できません。'
  end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/admin/reviews/edit.html.erb
<div class="container mt-4">
  <h1>レビュー編集</h1>

  <%= form_with(model: @review, url: admin_review_path(@review), method: :patch) do |form| %>
    <div class="form-group">
      <%= form.label :rating %>
      <%= form.number_field :rating, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :comment %>
      <%= form.text_area :comment, class: 'form-control' %>
    </div>

    <%= form.submit '更新', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/reviews/index.html.erb
<div class="container mt-4" style="min-height: 660px;">
  <h1>レビュー一覧</h1>

  <table class="table">
    <thead>
      <tr>
        <th>映画</th>
        <th>評価</th>
        <th>コメント</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.movie.title %></td>
          <td><%= review.rating %>/5点</td>
          <td><%= review.comment %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '編集', edit_admin_review_path(id: review.id), class: 'btn btn-secondary btn-sm mr-1' %>
              <%= button_to '削除', admin_review_path(id: review.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm mr-2' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class = "row">
    <div class = "my-5 text-center" style="max-width: 500px; margin: 0 auto;">
      <%= paginate @reviews %>
    </div>
</div>