config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'users/show'
  end
  devise_for :admins, controllers: {
  registrations: "admins/registrations",
  sessions: "admins/sessions",
  passwords: "admins/passwords"
  }

  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords"
  }

  devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :movies, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :user do
    root to: 'homes#top'
    get "/about" =>"homes#about"
    resources :movies, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy] do
        resources :users, only: [:show]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["genres_name", "title", "overview"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["genres_name", "title", "overview"]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :rating, presence: true
  validates :comment, length: { minimum: 1, maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  attribute :is_active, :boolean

  def username
    name
  end

  def guest?
    persisted? ? false : true
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = Kaminari.paginate_array(User.all).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'ユーザー情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除しました。'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user_or_admin!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  helper_method :guest_user?

  def authenticate_user_or_admin!

  if request.path.start_with?('/admin')
   authenticate_admin!
  else
   authenticate_user!
  end

  end

  def set_search
    @q_header = Movie.ransack(params[:q_header])
  end

  def after_sign_in_path_for(resource)
    movies_path
  end


  def guest_user?
    !user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @movies = Movie.all.order(created_at: :desc).limit(9)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user! # ユーザーがログインしていることを確認
  

  def show
    @user = User.find(params[:id])  # レビューに関連するユーザーの情報を取得
    @reviews = @user.reviews.page(params[:page]).per(5)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/movies_helper.rb
module User::MoviesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid pb-1" style="background-color:#000000;">
    <div class="text-center pt-3">
      <%= link_to "https://twitter.com/", class: "text-decoration-none" do %>
        <i class="fab fa-twitter-square h2 text-light"></i>
      <% end %>

      <%= link_to "https://www.facebook.com/", class: "text-decoration-none mx-2" do %>
        <i class="fab fa-facebook h2 text-light"></i>
      <% end %>

      <%= link_to "https://www.instagram.com/", class: "text-decoration-none" do %>
        <i class="fab fa-instagram-square h2 text-light"></i>
      <% end %>

      <%= link_to "https://line.me/ja/", class: "text-decoration-none ml-2" do %>
        <i class="fab fa-line h2 text-light"></i>
      <% end %>
    </div>
    <div class="text-center">
      <span class="text-light">©Copyright 2023 eiga ALL Rights reserved.</span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<head>
<style>
  .logo-text {
  font-family: "Arial", sans-serif;
  font-size: 32px;
  font-weight: bold;
  color: #ffffff;
  text-transform: uppercase;
  animation: neonEffect 1.5s ease-in-out infinite alternate;
}

@keyframes neonEffect {
  from {
    text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #ff00de, 0 0 80px #ff00de, 0 0 90px #ff00de, 0 0 100px #ff00de, 0 0 150px #ff00de;
  }
  to {
    text-shadow: 0 0 5px #ffffff, 0 0 10px #ffffff, 0 0 20px #ffffff, 0 0 40px #00c3ff, 0 0 80px #00c3ff, 0 0 90px #00c3ff, 0 0 100px #00c3ff, 0 0 150px #00c3ff;
  }
}

</style>
</head>
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#000000;">
    <div class="ml-5">
      <a class="navbar-brand" href="/">
      <span class="logo-text">eiga</span>
      </a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <div class="text-light mt-2 ml-3">
        <strong><%= current_user.name %></strong> , Welcome！
        </div>
        <li class="mr-3">
          <%= link_to "映画一覧", movies_path,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "my page", user_users_show_path(id: current_user.id),class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
      <% elsif admin_signed_in? %>
        <div class="text-light mt-2 ml-3">
        <strong>管理者ログイン中</strong>
        </div>
        </li>
        <li class="mr-3">
          <%= link_to "NEW MOVIE", admin_movies_path, class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "user一覧", admin_users_path, class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "review一覧", admin_reviews_path, class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
      <% else %>
        <li class="mr-3">
          <%= link_to "新規登録", new_user_registration_path,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
        <li class="mr-3">
          <%= link_to "ログイン", new_user_session_path,class: 'nav-link text-body mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
      <% end %>
      </ul>
      <% if user_signed_in? %>
      <%= render 'user/homes/search', q_header: @q_header %>
      <% else %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eiga</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="background-color:white">
    <header>
      <style>
       header{font-family: 'Noto Serif JP', serif;}
      </style>
        <%= render 'layouts/header' %>
    </header>
    <div style="background-color:#000000;">
      <div class="text-light ml-5">
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </div>
    </div>

    <main>
    <%= yield %>
    </main>

      <style>
        footer{font-family: 'Noto Serif JP', serif;}
      </style>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>