config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'users/show'
  end
  devise_for :admins, controllers: {
  registrations: "admins/registrations",
  sessions: "admins/sessions",
  passwords: "admins/passwords"
  }

  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords"
  }

  devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :movies, only:[:index, :show, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :user do
    root to: 'homes#top'
    get "/about" =>"homes#about"
    resources :movies, only: [:index, :show] do
      resources :reviews, only: [:create, :destroy] do
        resources :users, only: [:show]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  attribute :is_active, :boolean

  def username
    name
  end

  def guest?
    persisted? ? false : true
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = Kaminari.paginate_array(User.all).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'ユーザー情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除しました。'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @movies = Movie.all.order(created_at: :desc).limit(9)
  end
end

app/controllers/user/movies_controller.rb
class User::MoviesController < ApplicationController

  def index
    @q_header = Movie.ransack(params[:q])
    @movies = @q_header.result(distinct: true).order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @movie = Movie.find(params[:id])
    @review = Review.new
    @reviews = @movie.reviews.includes(:user).where(user: {is_active: true}).order(created_at: :desc)
  end

  def create_review
    @movie = Movie.find(params[:id])
    @review = @movie.reviews.build(review_params)
    if @review.save
      redirect_to movie_path(@movie), notice: 'レビューが投稿されました。'
    else
      render :show
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to movie_path(@movie), notice: 'コメントが作成されました。'
    else
      redirect_to request.referer, alert: '入力してください！'
    end
  end

  def destroy
  @review = Review.find(params[:id])
  if @review.user == current_user
    @review.destroy
    redirect_to movie_path(@review.movie), notice: 'レビューが削除されました。'
  else
    redirect_to movie_path(@review.movie), alert: '他のユーザーのレビューは削除できません。'
  end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user! # ユーザーがログインしていることを確認
  

  def show
    @user = User.find(params[:id])  # レビューに関連するユーザーの情報を取得
    @reviews = @user.reviews.page(params[:page]).per(5)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to movies_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def create
    user = User.find_by(email: params[:user][:email])

    if user && user.valid_password?(params[:user][:password])
      if user.is_active?
        sign_in user
        redirect_to movies_path, notice: 'ログインしました。'
      else
        redirect_to new_user_session_path, alert: '退会済みのためログインできません。'
      end
    else
      redirect_to new_user_session_path, alert: 'メールアドレスまたはパスワードが正しくありません。'
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/movies_helper.rb
module User::MoviesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h1>Edit User</h1>

  <%= form_with(model: @user, url: admin_user_path(@user), method: :patch) do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <label for="user_is_active">会員ステータス:</label><br>
      <%= form.radio_button :is_active, true, id: "user_is_active" %>
      <%= form.label :is_active, "有効" %><br>
      <%= form.radio_button :is_active, false, id: "user_is_inactive" %>
      <%= form.label :is_active, "退会" %>
    </div>

    <div class="form-group">
      <%= form.submit "Update User", class: "btn btn-primary" %>
      <%= link_to "Cancel", admin_user_path(@user), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="text-center" style="margin-top: 50px; height: 600px;">
  <table class="table">
    <thead>
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>会員ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.is_active ? '有効' : '退会' %></td>
          <td>
            <%= link_to '詳細', admin_user_path(user), class: 'btn btn-primary btn-sm me-1' %>
            <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-secondary btn-sm me-1' %>
            <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm me-1' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class = "row">
    <div class = "my-5 text-center" style="max-width: 500px; margin: 0 auto;">
     <%= paginate @users %>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">ユーザー詳細</h5>
        </div>
        <div class="card-body">
          <p><strong>名前:</strong> <%= @user.name %></p>
          <p><strong>メールアドレス:</strong> <%= @user.email %></p>
          <p><strong>会員ステータス:</strong> <%= @user.is_active ? '有効' : '退会' %></p>
          <!-- 他のユーザー詳細情報を表示する場合はここに追加 -->
        </div>
        <div class="card-footer">
          <%= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary' %>
          <%= link_to '一覧に戻る', admin_users_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>